name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'todo-app/**'  # only trigger when app code changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./todo-app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/argocd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/argocd:${{ github.sha }}

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image:.*argocd.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/argocd:${{ github.sha }}|" app/deployment.yaml

      - name: Commit updated deployment.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add app/deployment.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}"
          git push
